version: "3"

services:
  nginx:
    build:
      context: ./docker/ngnix
      dockerfile: Dockerfile
    container_name: nginx_bs
    ports:
      - "81:80"
    depends_on:
      - mysql
      - python
    volumes:
      - ./static/:/static
      - ./media/:/media

  python:
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    container_name: python_bs
    command: gunicorn templateBS.wsgi:application -b 0.0.0.0:8000 --reload
    volumes:
      - ./:/django_app
    ports:
      - "8001:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: mysql_bs
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/dump:/tmp/dump
      - ./tmp/log/docker:/var/log/mysql
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: template_bs
      MYSQL_ROOT_PASSWORD: DfyLthCfhyjvth1
      TZ: UTC
