# Generated by Django 4.2 on 2023-05-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citymailsend',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='urlscontent',
            name='user_created',
        ),
    ]
