# Generated by Django 4.2 on 2023-04-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_url', models.URLField(max_length=60, verbose_name='Ссылка на мероприятие')),
            ],
        ),
        migrations.CreateModel(
            name='UrlsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('rate', models.CharField(max_length=4, verbose_name='Возрастной ценз')),
                ('date_event', models.CharField(max_length=20, verbose_name='Дата мероприятия')),
                ('time_event', models.CharField(max_length=20, verbose_name='Время мероприятия')),
                ('venue', models.CharField(max_length=50, verbose_name='Место проведения')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('content_text', models.TextField(max_length=300, verbose_name='Описание мероприятия')),
                ('poster_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.urlsposter')),
            ],
        ),
    ]
