# Generated by Django 4.2 on 2023-05-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_citymailsend_user_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StarPlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.planet')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.star')),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='planets',
            field=models.ManyToManyField(blank=True, through='main.StarPlanet', to='main.planet'),
        ),
        migrations.CreateModel(
            name='GalaxieStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.galaxie')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.star')),
            ],
        ),
        migrations.AddField(
            model_name='galaxie',
            name='stars',
            field=models.ManyToManyField(blank=True, through='main.GalaxieStar', to='main.star'),
        ),
    ]
