# Generated by Django 4.2 on 2023-05-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_galaxie_planet_star_starplanet_star_planets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxiestar',
            name='galaxie',
        ),
        migrations.RemoveField(
            model_name='galaxiestar',
            name='star',
        ),
        migrations.RemoveField(
            model_name='star',
            name='planets',
        ),
        migrations.RemoveField(
            model_name='starplanet',
            name='planet',
        ),
        migrations.RemoveField(
            model_name='starplanet',
            name='star',
        ),
        migrations.DeleteModel(
            name='Galaxie',
        ),
        migrations.DeleteModel(
            name='GalaxieStar',
        ),
        migrations.DeleteModel(
            name='Planet',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
        migrations.DeleteModel(
            name='StarPlanet',
        ),
    ]
