# Generated by Django 4.2 on 2023-05-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_galaxiestar_galaxie_remove_galaxiestar_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlscontent',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.citymailsend'),
            preserve_default=False,
        ),
    ]
