# Generated by Django 4.2 on 2023-05-19 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_urlscontent_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlscontent',
            name='city',
        ),
        migrations.AlterField(
            model_name='datemailsend',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_select', to='main.citymailsend'),
        ),
        migrations.AlterField(
            model_name='datemailsend',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urlscontent',
            name='date_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='main.datemailsend'),
        ),
    ]
